#!/usr/bin/env bash

confirm="${1:-n}"
defaultUserSettings=user_settings.conf
user_settings_conf="${SLURM_USER_SETTINGS:-$defaultUserSettings}"

# Slurm account configuration file:
defaultAccountSettings=accounts.conf
accounts_conf=${SLURM_ACCOUNT_SETTINGS:-$defaultAccountSettings}

# run slurmusersettings
update_commands=$(SLURM_ACCOUNT_SETTINGS=$accounts_conf SLURM_USER_SETTINGS=$user_settings_conf slurmaccounts) || exit 1
newline=$'\n\n'
update_commands=${update_commands}${newline}$(SLURM_ACCOUNT_SETTINGS=$accounts_conf SLURM_USER_SETTINGS=$user_settings_conf slurmusersettings -n) || exit 1
echo "$update_commands"

if [[ $confirm == "-y" ]]; then
  eval "$update_commands"
  echo
  echo "Done."
elif [[ $confirm == "-n" ]]; then
  echo "Aborting."
else
  echo '
==============================================================
PLEASE CHECK THE ABOVE OUTPUT CAREFULLY!
==============================================================


  '
  read -p "Apply changes to slurm accounting database? (y/n)" -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    # do dangerous stuff
    eval "$update_commands"
    echo
    echo "Done."
  else
    echo "Update aborted."
  fi
fi
